Lab1v1
MKristina/Networks pull request #2
Opened 2020-09-22 12:02 UTC by MKristina

@Aloomenon

2020-09-24 15:23 UTC, Aloomenon requested changes

2020-09-24 15:23 UTC, Aloomenon commented on Lab1/UDPManager.java
> +                    socket.getSocket().receive(recDatagramPacket);
В чем разница использования 1 сокета для отправки-получения от использования двух сокетов: 1 - отправляет, а второй читает.

Запускали на 3+ клиентах?

2020-09-27 06:50 UTC, MKristina commented on Lab1/UDPManager.java
> +                    socket.getSocket().receive(recDatagramPacket);
Запускала на трех,больше не нашлось
Вопрос очень интересный на самом деле, есть несколько предположений
Во-первых, разница в реализации лабы и количестве используемых ресурсов
Так же, возможно, если у нас один сокет, и поступит, например, блокирующий сигнал, то чтение/запись могут сломаться 
А разделенные прием и передача обеспечивают более надежную работу

2020-09-27 06:52 UTC, MKristina commented on Lab1/UDPManager.java
> +                    socket.getSocket().receive(recDatagramPacket);
@Aloomenon

2020-09-27 09:50 UTC, Aloomenon commented
Ок, принял. Фамилию имя скажите

2020-09-27 10:16 UTC, MKristina commented
Мелешко Кристина, 18204
@Aloomenon

2020-10-25 09:05 UTC, Aloomenon commented
Этот PR можно закрывать

2020-10-27 05:55 UTC, closed without merging