Add files via upload
MKristina/Networks pull request #3
Opened 2020-10-19 13:08 UTC by MKristina

@Aloomenon

2020-10-22 07:42 UTC, MKristina commented
@Aloomenon

2020-10-25 09:08 UTC, Aloomenon requested changes

2020-10-25 09:08 UTC, Aloomenon commented on Client.java
> +            inputFile.close();
IOException может вылететь раньше, что мы не сможем закрыть этот поток?

2020-10-27 06:02 UTC, MKristina commented on Client.java
> +            inputFile.close();
Да, действительно такое могло быть. Добавила закрытие потока при exception
@Aloomenon

2020-11-02 09:09 UTC, MKristina commented on Client.java
> +            inputFile.close();
@Aloomenon

2020-11-07 20:23 UTC, Aloomenon commented
ок. Принял

2020-11-10 13:42 UTC, closed without merging