lab3
MKristina/Networks pull request #4
Opened 2020-11-10 13:41 UTC by MKristina

@Aloomenon

2020-11-14 08:47 UTC, Aloomenon commented
Не увидел освобождения ресурсов.

2020-11-14 08:51 UTC, Aloomenon requested changes

2020-11-14 08:51 UTC, Aloomenon commented on Lab3/Master/RecvMaster.java
> +                    case SEND_FOSTER_MESSAGE : {
что это делает?

2020-11-14 08:51 UTC, Aloomenon commented on Lab3/Master/RecvMaster.java
> +                    case ACCEPT_CHILD_MESSAGE : {
Зачем это?

2020-11-14 08:51 UTC, Aloomenon commented on Lab3/Main/Packet.java
> +        ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(recvPacket.getData()));
Кодировка не нужна?

2020-11-20 07:20 UTC, MKristina commented on Lab3/Master/RecvMaster.java
> +                    case SEND_FOSTER_MESSAGE : {
При получении ping-сообщения мы обновляем время получения последнего пинга у отправителя в списке живых соседей

2020-11-20 07:21 UTC, MKristina commented on Lab3/Master/RecvMaster.java
> +                    case ACCEPT_CHILD_MESSAGE : {
в switch-е мы определяем тип получаемого сообщения

2020-11-21 14:47 UTC, MKristina commented on Lab3/Main/Packet.java
> +        ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(recvPacket.getData()));
Вообще нужна, если у нас будет какой-нибудь клиент, кто будет писать не в utf-8 (она по умолчанию)

2020-11-21 14:51 UTC, Aloomenon requested changes

2020-11-21 14:51 UTC, Aloomenon commented on Lab3/Master/RecvMaster.java
> +                    case ACCEPT_CHILD_MESSAGE : {
Какие типы сообщений есть?

2020-11-21 15:32 UTC, MKristina commented on Lab3/Master/RecvMaster.java
> +                    case ACCEPT_CHILD_MESSAGE : {
ACCEPT_CHILD_MESSAGE:
Сообщение, при получении которого, нода получает родителя.
ADOPT_CHILD_MESSAGE
Сообщение, при получении которого, нода добавляет отправителя в список детей и отправляет подтверждение 
этого действия (ACCEPT_CHILD_MESSAGE), делает отправителя своим заместителем, если такого
еще не было, отправляет отправителю ноду, которая "усыновит" его в случае "смерти" данной
ноды.
CHAT_MESSAGE:
Сообщение, которое вводится в консоль для отправки по дереву.
ACCEPT_CHAT_MESSAGE:
Сообщение, подтверждающее получение чат-сообщения (CHAT_MESSAGE).
PING_MEESAGE:
Сообщение, подтверждающее жизнеспособность отправителя. (обновляем время получения последнего пинга у отправителя в списке живых соседей)
SEND_FOSTER_MESSAGE:
Сообщение, в котором "ребенку" текущей ноды отправляется "усыновитель" в случае "смерти"
ноды-отправителя (родителя).
CONFIRM_FOSTER_MESSAGE:
Сообщение-подтверждение получения сообщения об усыновителе (SEND_FOSTER_MESSAGE).

2020-11-21 19:12 UTC, MKristina commented
@Aloomenon

2020-11-24 07:11 UTC, Aloomenon commented
Можно ли реализовать без первых двух и пинга?

On Sat, 21 Nov 2020, 22:13 MKristina, <notifications@github.com> wrote:

> @Aloomenon <https://github.com/Aloomenon>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MKristina/Networks/pull/4#issuecomment-731623351>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGF7IC7P4USD7JUHMYWFFY3SRAGMPANCNFSM4TQVS4IA>
> .
>

2020-11-24 12:16 UTC, MKristina commented
Теоретически можно и без них 
@Aloomenon

2020-11-24 19:16 UTC, Aloomenon commented
Значит время проверить на практике!

2020-12-01 16:44 UTC, MKristina commented
@Aloomenon

2020-12-02 15:30 UTC, Aloomenon commented
Ок, принял

On Tue, 1 Dec 2020, 19:44 MKristina, <notifications@github.com> wrote:

> @Aloomenon <https://github.com/Aloomenon>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MKristina/Networks/pull/4#issuecomment-736673181>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGF7IC66XRXRZAFYW2JWBNLSSUMOXANCNFSM4TQVS4IA>
> .
>

2020-12-06 13:10 UTC, closed without merging